from typing import List

class Parameters:
    POPULATION_SIZE: int = 360
    INITIAL_PROGRAM_POPULATION: int = 1000
    POPGAP: float = 0.5
    ACTIONS: List[str] = [ "DO_NOTHING", "FIRE_LEFT", "FIRE_MAIN", "FIRE_RIGHT" ]
    NUM_OBSERVATIONS: int = 8
    NUM_REGISTERS: int = 8
    DELETE_INSTRUCTION_PROBABILITY: float = 0.7
    ADD_INSTRUCTION_PROBABILITY: float = 0.7
    SWAP_INSTRUCTION_PROBABILITY: float = 1.0
    MUTATE_INSTRUCTION_PROBABILITY: float = 1.0
    ADD_PROGRAM_PROBABILITY = 0.7
    DELETE_PROGRAM_PROBABILITY = 0.7
    NEW_PROGRAM_PROBABILITY = 0.1
    MUTATE_PROGRAM_PROBABILITY = 0.2
    TEAM_POINTER_PROBABILITY = 0.5
    MAX_INSTRUCTION_COUNT = 96
    MAX_INITIAL_TEAM_SIZE = 5
    
    
