name: run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to benchmark against (e.g. Frostbite, LunarLander-v2)'
        required: true
      population_size:
        description: 'The number of root teams in every generation'
        required: true
        default: '360'
      actions:
        description: 'A comma separated list of actions used in the environment. Omit this argument for Atari' 
        required: false
      num_observations:
        description: 'The size of the input/feature space'
        required: True
      num_generations:
        description: 'The number of generations the model will be trained for.'
        required: True
      max_steps:
        description: 'The number of interactions an agent can have with its environment before termination'
        required: true
        default: '500'
      generation:
        description: 'The number that the generation counter should be initialized to. (helpful when loading/saving a model'
        required: false
        default: '1'
      model:
        description: 'The path to the model file to load.' 
        required: false

jobs:
  deploy:

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install -e .
            
      - name: Run
        run: |
          python main.py \
          --environment ${{github.event.inputs.environment}} \
          --population_size ${{github.event.inputs.population_size}} \
          --num_observations ${{github.event.inputs.num_observations}} \
          --num_generations ${{github.event.inputs.num_generations}} \
          --max_steps ${{github.event.inputs.max_steps}} \
          {% if github.event.inputs.actions %}--actions ${{github.event.inputs.actions}}{% endif %} \
          {% if github.event.inputs.generation %}--generation ${{github.event.inputs.generation}}{% endif %} \
          {% if github.event.inputs.model %}--model ${{github.event.inputs.model}}{% endif %}
