name: run

on:
  workflow_dispatch:
    inputs:
      NUM_GENERATIONS:
        description: 'Number of generations'
        required: false
        default: '200'
      MAX_STEPS:
        description: 'Maximum amount of steps'
        required: false
        default: '1000'
      POPULATION_SIZE:
        description: 'The population size'
        required: false
        default: '360'
      ACTIONS:
        description: 'The actions list'
        required: false
        default: '["LEFT", "RIGHT"]'
      ENVIRONMENT:
        description: 'The environment'
        required: false
        default: 'CartPole-v1'
      NUM_OBSERVATIONS:
        description: 'The number of observations'
        required: false
        default: '4'

jobs:
  deploy:
    timeout-minutes: 4320
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install -e .
            
      - name: Run
        run: |
          python main.py --NUM_GENERATIONS ${{github.event.inputs.NUM_GENERATIONS}} --MAX_STEPS ${{github.event.inputs.MAX_STEPS}} --POPULATION_SIZE ${{github.event.inputs.POPULATION_SIZE}} --ACTIONS ${{github.event.inputs.ACTIONS}} --ENVIRONMENT ${{github.event.inputs.ENVIRONMENT}} --NUM_OBSERVATIONS ${{github.event.inputs.NUM_OBSERVATIONS}}
